image: infinitecoding/platformio-for-ci:latest

pipelines:
  branches:
    main:
      - step:
          name: Build and Upload Binary
          script:
            # install command-line JSON processor
            - apt update && apt install -y jq

            # Fetch the version from version.txt
            - VERSION_FILE="version.txt"
            - if [ -f "$VERSION_FILE" ]; then
              VERSION=$(cat $VERSION_FILE);
              else
              echo "version.txt file not found!";
              exit 1;
              fi
            - echo "Current version = $VERSION"

            # Fetch the list of files in the Downloads section
            - RESPONSE=$(curl -s -u "$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD" "https://api.bitbucket.org/2.0/repositories/$BITBUCKET_WORKSPACE/$BITBUCKET_REPOSITORY/downloads")

            # Parse the latest file uploaded
            - LATEST_FILES=$(echo "$RESPONSE" | jq -r '.values | sort_by(.created_on) | last(.[]).name')
            - echo "Latest uploaded files = $LATEST_FILES"

            # Check if the latest file matches the current version's binary
            - FIRMWARE_BIN="${VERSION}_firmware.bin"
            - LITTLEFS_BIN="${VERSION}_littlefs.bin"

            - if echo "$LATEST_FILES" | grep -q "$FIRMWARE_BIN" && echo "$LATEST_FILES" | grep -q "$LITTLEFS_BIN"; then
              echo "Both binary files already exist as the latest upload. Skipping upload.";
              exit 0;
              fi

            # Run PlatformIO build
            - platformio run
            - platformio run --target buildfs

            # Find the generated binary files
            - FIRMWARE_PATH=$(find .pio -name "firmware.bin" | head -n 1)
            - LITTLEFS_PATH=$(find .pio -name "littlefs.bin" | head -n 1)

            # Check if both files were generated
            - if [ ! -f "$FIRMWARE_PATH" ] || [ ! -f "$LITTLEFS_PATH" ]; then
              echo "One or both binary files not found!";
              exit 1;
              fi

            # Upload firmware.bin
            - echo "Uploading firmware $FIRMWARE_BIN"
            - curl -u "$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD" -X POST "https://api.bitbucket.org/2.0/repositories/$BITBUCKET_WORKSPACE/$BITBUCKET_REPOSITORY/downloads" -F "files=@$FIRMWARE_PATH;filename=${FIRMWARE_BIN}"

            # Upload littlefs.bin
            - echo "Uploading LittleFS $LITTLEFS_BIN"
            - curl -u "$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD" -X POST "https://api.bitbucket.org/2.0/repositories/$BITBUCKET_WORKSPACE/$BITBUCKET_REPOSITORY/downloads" -F "files=@$LITTLEFS_PATH;filename=${LITTLEFS_BIN}"
